[project]
name = "pyBLUP"
version = "1.0.0"
dependencies = [
    "numpy","scipy",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/pyBLUP"]